### ISSUE TITLE
make it clearer that there'll be two RStudio projects

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/pkgreviewr#10]
I think it wasn't 100% clear in my head at first. This is either a suggestion for the docs or a way for you to see I got it all wrong :joy:

The README could state that the goal of this package is to help you create an RStudio project with the review, and to automatically setup a second RStudio project with the package. The reviewing will happen by juggling between the two projects. The review package itself will help you go through the review by having all steps lined out in a document where you can record your answers and tests. _In the future: it will also help you submit your review automatically._

**Comment by annakrystalli** [comment]
Agreed, i flag the second directory creation more clearly . Although to be fair, the `index` notebook in the review project is setup so you can do all the testing within it. ie the path to the package source code is automatically set within the r chunks of the notebook so you can do all testing and checks in using `devtools` functions, in it by running the chunks. You don't actually have to look too much at the local package source (although of course you could), you just need it to be at a particular path. The index workbook links to all the relevant files online in the repo for inspection. I find that approach easier for me.
