### ISSUE TITLE
Dependency on RStudio

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/pkgreviewr#11]
I am 100% ok with this package depending on RStudio.

That said I'm looking at `workflowr` and it says  "Note that while you do not need to use RStudio with workflowr, do not delete the Rproj file because it is required by other functions.". I'm not sure if it means that it can work without RStudio installed?

And in any case a warning in the docs might be useful (and potentially one in the code? can one run a function to know whether RStudio is installed? `rstudioapi::isAvailable()` only says whether it's running).

In `workflowr` code they also [check the RStudio version installed](https://github.com/jdblischak/workflowr/blob/master/R/wflow_start.R#L195).

This issue is not urgent at all but I preferred writing down what I saw in their code before I forgot about it.

**Comment by annakrystalli** [comment]
Dependency flagged in README for the time being but I'm going to write a test to check for it.

**Comment by annakrystalli** [comment]
Add function to check for rstudio and rstudio version ea72fd543d85bfd93fdeec79138b1b152d450d83
