### ISSUE TITLE
Missing GH parameters will not load index.Rmd, README.md

### ISSUE THREAD

**Issue by timtrice** [ropenscilabs/pkgreviewr#16]
## Issue

If GitHub global configs `user.name` and `user.email` are not set then `pkgreview_init` will not generate the **index.Rmd** and **README.md** file as specified in the README. 

```r
pkgreview_init()
```

Setting the parameters and running `pkgreview_init()` again does not resolve the issue. When asked if I wish to over-write the existing project and selectin "Yes" (or a variation thereof), 

> Error in fallback_or_stop(fallback, "Cannot find GitHub username for email") : 
>  Cannot find GitHub username for email

## Reprex

Using Docker and rocker/tidyverse:3.4.3, 

From terminal:

```
git config --global user.name "Mona Lisa"
```

Within RStudio:

```r
devtools::install_github("ropenscilabs/pkgreviewr")

pkgreviewr::pkgreview_create(pkg_repo = "cboettig/rdflib", review_parent = "~/")
```

After reload:

```r
library(pkgreviewr)
pkgreview_init(pkg_repo = "cboettig/rdflib")
```

>  Error in default_signature(repo) : 
>   Error in 'git2r_signature_default': config value 'user.email' was not found

In terminal:

```
git config --global user.email "example@mail.com"
```

RStudio:

```r
pkgreview_init(pkg_repo = "cboettig/rdflib")
```

> Overwrite pre-existing file 'rdflib'?
> 1: No way
> 2: Not now
> 3: Yup

Select 3.

```
✔ Writing 'pkgreview.md'
● Modify 'pkgreview.md'
```

> Error in fallback_or_stop(fallback, "Cannot find GitHub username for email") : 
>   Cannot find GitHub username for email

## Session Info

**R version 3.4.3 (2017-11-30)**

**Platform:** x86_64-pc-linux-gnu (64-bit) 

**locale:**
_LC_CTYPE=en_US.UTF-8_, _LC_NUMERIC=C_, _LC_TIME=en_US.UTF-8_, _LC_COLLATE=en_US.UTF-8_, _LC_MONETARY=en_US.UTF-8_, _LC_MESSAGES=C_, _LC_PAPER=en_US.UTF-8_, _LC_NAME=C_, _LC_ADDRESS=C_, _LC_TELEPHONE=C_, _LC_MEASUREMENT=en_US.UTF-8_ and _LC_IDENTIFICATION=C_

**attached base packages:** 
_stats_, _graphics_, _grDevices_, _utils_, _datasets_, _methods_ and _base_

**other attached packages:** 
pkgreviewr(v.0.1.0)

**loaded via a namespace (and not attached):** 
_Rcpp(v.0.12.15)_, _rstudioapi(v.0.7)_, _knitr(v.1.19)_, _magrittr(v.1.5)_, _usethis(v.1.2.0)_, _devtools(v.1.13.4)_, _R6(v.2.2.2)_, _httr(v.1.3.1)_, _stringr(v.1.2.0)_, _tools(v.3.4.3)_, _git2r(v.0.21.0)_, _withr(v.2.1.1)_, _htmltools(v.0.3.6)_, _yaml(v.2.1.16)_, _rprojroot(v.1.3-2)_, _digest(v.0.6.15)_, _assertthat(v.0.2.0)_, _crayon(v.1.3.4)_, _whoami(v.1.1.2)_, _ini(v.0.3.0)_, _bitops(v.1.0-6)_, _clisymbols(v.1.2.0)_, _curl(v.3.1)_, _RCurl(v.1.95-4.10)_, _memoise(v.1.1.0)_, _evaluate(v.0.10.1)_, _rmarkdown(v.1.8)_, _gh(v.1.0.1)_, _stringi(v.1.1.6)_, _pander(v.0.6.1)_, _compiler(v.3.4.3)_, _desc(v.1.1.1)_, _backports(v.1.1.2)_ and _jsonlite(v.1.5)_

**Comment by annakrystalli** [comment]
🤔 curious.

Thanks for letting me know. Will look into it.

**Comment by annakrystalli** [comment]
Hi @timtrice,

I've added a check (commit a5af6059add703ba108dc9cb142186253eb88844)  before initialisation that haults the function is global gh_username credentials aren't detected with an informative error message. Configuring the git global settings and rerunning the function works for me.  Hopefully it works for you too?
