### ISSUE TITLE
Needs Testing suite!

### ISSUE THREAD

**Issue by annakrystalli** [ropenscilabs/pkgreviewr#2]

**Comment by llrs** [comment]
I saw your [tweet](https://twitter.com/annakrystalli/status/956578062296117250), what do you want to check ? Do you want to use testthat or RUnit. As I assume that you will say testthat, have you read the Hadley page on [testing](http://r-pkgs.had.co.nz/tests.html)?

**Comment by annakrystalli** [comment]
Hello! And many thanks for your response! 

I'm traveling at the moment but will detail my main concerns setting up tests for some of the functionality this eve. Hopefully you might be able to help! 😃

**Comment by annakrystalli** [comment]
Also, I'll be using testthat.

**Comment by annakrystalli** [comment]
Hi @llrs! So in thinking about how to explain my question I had a [rubber duck debugging](https://en.wikipedia.org/wiki/Rubber_duck_debugging) moment and solved my problem 😜

There's a start to a [testing suite](https://github.com/ropenscilabs/pkgreviewr/blob/master/tests/testthat/test-my-test.R) now. More and better tests are still required though, so if you have any suggestions on this they are more than welcome. But thanks for showing an interest and offering help in the first place!

**Comment by llrs** [comment]
Glad you found your way! Remember to change the context of your test, to understand what are you testing.

I don't know your package well enough to propose new test, but if I came up with something I'll send a pull request.
