### ISSUE TITLE
README comments

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/pkgreviewr#26]
Just add that it's to facilitate the work of _reviewers_? I know it's sort of implied by saying "reviews" but later when there are tools to facilitate the work of authors and editors (I'll probably implement these in separate packages), there could be some confusion?

**Comment by maelle** [comment]
I mean in the first sentence "facilitate reviews", maybe add "is a helper for reviewers"?

**Comment by maelle** [comment]
Other comments:

* github -> GitHub

* suggest the use of `usethis::use_git_config`?

* when mentioning the review project for the first time in workflow, say what it is?

* should index.Rmd be renamed into something easier to understand?

* I was wondering whether it makes sense to have the html on GitHub, could there also be a .md?

**Comment by maelle** [comment]
mmmh my comment about the html was stupid, now that I've read the vignette I know it'll be rendered via gh-pages 😍  maybe "pushed to GitHub for publication." -> "pushed to GitHub for publication via gh-pages"?

**Comment by maelle** [comment]
* In general I am in favor of short READMEs, and since the README wouldn't be available to someone who installed the package, I'd recommend shortening the README and moving part of its content to a "Get started" vignette.

**Comment by maelle** [comment]
adding to my previous comments, 

* I think a "get started" vignette is even more important now that there's another article about something else.

* Could you add a link to ropensci/onboarding and to https://ropensci.github.io/dev_guide/ ?

* When mentioning the git global config, maybe add http://usethis.r-lib.org/articles/articles/usethis-setup.html as further resources? (since it'd help making one's workflow even easier)

* When mentioning `reprex` add a link to https://reprex.tidyverse.org/ ?

* I think it's confusing that one can take note in either index or in the review, maybe add a few points about how to choose (depending on the note I guess)?

**Comment by maelle** [comment]
* typo "defned"

* for all vignettes link to the pkgdown versions?

**Comment by annakrystalli** [comment]
OK, I agree with all this. Will tackle an overhaul of README and a Getting started vignette asap.
