### ISSUE TITLE
add some checks when downloading files

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/pkgreviewr#30]
E.g. when downloading the template, try again a few times?

**Comment by maelle** [comment]
I broke this since the templates are now in the appendix of `dev_guide`... the best might be to have a regularly updated copy in inst/... I'm sorry!

Or in a central place that'd be read by `dev_guide` too?

**Comment by annakrystalli** [comment]
We fixed this in dev_guide (ie they are standalone files now) and I've updated the URL in `pkgreviewr` so I'll close this issue. 💪
