### ISSUE TITLE
Write function to extract repo metadata using github API V4

### ISSUE THREAD

**Issue by annakrystalli** [ropenscilabs/pkgreviewr#41]
## Resources

- [API docs](https://developer.github.com/v4/)
    + repo [metadata](https://developer.github.com/v4/object/repository/)
- [tidyverse repository dashboard](https://connect.rstudioservices.com/jimhester/tidyverse_dashboard/tidyverse_dashboard.html)
    + In particular [these template queries](https://github.com/jimhester/tidyversedashboard/tree/master/inst)
- [Maelle's post](https://ropensci.org/blog/2018/04/26/rectangling-onboarding/)

**Comment by maelle** [comment]
Possibly related to https://github.com/ropensci/codemetar/issues/20 depending on what kind of metadata you want (not sure which API I'll use for `codemetar` 🤔 )

**Comment by annakrystalli** [comment]
In the end this is overkill. I can get all the data I need with a simple `gh` call l to query the repo. Will need to find another graphQL project! 😜
