### ISSUE TITLE
Not able to create a project on Windows

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/pkgreviewr#43]
cf https://github.com/r-lib/whoami/issues/4

**Comment by annakrystalli** [comment]
Related to issue noted in #25 by @tdjames1.   @tdjames1, out of curiosity, what does `system("git config --global --list", intern = TRUE)` return on your machine?

**Comment by tdjames1** [comment]
Hey @annakrystalli, here's the abbreviated output:
```
> system("git config --global --list", intern = TRUE)
[1] "user.name=T***** James"                                                                                                                                      
[2] "user.email=t*****@***********"                                                                                        
[3] "core.editor=emacs"   
<snip>
```

**Comment by maelle** [comment]
so does `whoami::email_address()` work on your machine?

**Comment by tdjames1** [comment]
Yes. 👍

**Comment by tdjames1** [comment]
Yes, but it is set as private. I figured that was why `whoami::gh_username()` couldn't find me so (as noted in #25) I tried setting up an authorization token to allow access to my email address (via GitHub > Settings > Developer settings > Personal access tokens) but that didn't resolve the problem.

**Comment by maelle** [comment]
@tjames1 now you can set an environment variable `GITHUB_USERNAME` cf https://github.com/r-lib/whoami
