### ISSUE TITLE
add code of conduct stuff as html comments

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/pkgreviewr#51]
so they don't need to be deleted but are still readable?

**Comment by annakrystalli** [comment]
Definitely should add a CoC and contributing page. Not sure what you mean with as html comments?

**Comment by annakrystalli** [comment]
Aha! I see. Nice idea. Do you think they need to delete it though? ie that there's a problem including it in a review report?

PS I totally misunderstood the initial comment...so now `pkgreviewr` has a code of conduct too! 😜

**Comment by annakrystalli** [comment]
Ok coming back to this I'm still not sure about the:
