### ISSUE TITLE
using `usethis::git_sitrep()` instead of `whoami::gh_username()`

### ISSUE THREAD

**Issue by benmarwick** [ropenscilabs/pkgreviewr#63]
Can I suggest using `usethis::git_sitrep()` instead of `whoami::gh_username()` here? Or are you waiting for the usethis git functions to become more robust first? I know they've been flakey for a long time!

https://github.com/ropenscilabs/pkgreviewr/blob/fb9df99b1c50ea00e9c434e82f97374ca9cb2e7e/R/github.R#L40

Seems that `whoami::gh_username()` depends on having `Sys.getenv("GITHUB_USERNAME")` non-empty. Mine was empty, but I see I can set it with `Sys.setenv(GITHUB_USERNAME = "benmarwick")`

I wonder why I need to since`usethis::git_sitrep()` gives a full output even when `Sys.getenv("GITHUB_USERNAME")` is empty. So mysterious!

Anyway, just a thought! 

```
sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pkgreviewr_0.1.1.9000

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2        rstudioapi_0.10   whisker_0.4       magrittr_1.5      usethis_1.5.1    
 [6] tidyselect_0.2.5  R6_2.4.0          rlang_0.4.0       httr_1.4.1        dplyr_0.8.3      
[11] tools_3.6.0       packrat_0.5.0     withr_2.1.2       git2r_0.26.1.9000 rprojroot_1.3-2  
[16] assertthat_0.2.1  tibble_2.1.3      crayon_1.3.4      whoami_1.3.0      purrr_0.3.2      
[21] base64enc_0.1-3   fs_1.3.1          clisymbols_1.2.0  triebeard_0.3.0   curl_4.0         
[26] glue_1.3.1        gh_1.0.1          compiler_3.6.0    pillar_1.4.2      urltools_1.7.3   
[31] desc_1.2.0        backports_1.1.4   jsonlite_1.6      pkgconfig_2.0.2  
```

**Comment by llrs** [comment]
Second, now I got to start a review and I couldn't follow the instructions because `pkgreview_create` failed due to `pkgreviewr:::check_global_git()` not finding my credentials/configuration while `usethis::git_sitrep` does.

**Comment by annakrystalli** [comment]
Thanks for your input both! 

It's an interesting suggestion. I'll be honest, I didn't know of `usethis::git_sitrep()` so love this tip! I had a quick play around and it doesn't seem like I can't easily capture the output of `usethis::git_sitrep()`. But under the hood it implements `gh::gh_whoami(usethis::github_token())` to detect GH credentials which I think is a bit more powerful than the `whoami` functions.

I've pushed changes to branch `devel`. Feedback welcome before I merge it into master!

**Comment by annakrystalli** [comment]
@maelle, this new implementation throws an error on TRAVIS because it's set up with your token. Any change you could help me swap it over?

**Comment by annakrystalli** [comment]
By the way @llrs, I'm curious, does `whoami::gh_username` not return anything for you? What about `git config user.name` in the terminal?

**Comment by annakrystalli** [comment]
@maelle , not to worry! Fixed now :)

**Comment by benmarwick** [comment]
Thanks! Yes, I think `usethis::git_sitrep()` is pretty new!

**Comment by annakrystalli** [comment]
OK, I've merged to master now. :)

**Comment by llrs** [comment]
@annakrystalli When I run `whoami::gh_username()` I get:

```
Error in fallback_or_stop(fallback, "Cannot find GitHub username for email") : 
  object 'fallback' not found
> traceback()
4: fallback_or_stop(fallback, "Cannot find GitHub username for email")
3: fun(arg, ...)
2: lookup_gh_username(email, token)
1: whoami::gh_username()
```

**Comment by annakrystalli** [comment]
Excellent! Well I'm glad it's working now and thanks for reporting the issue :)
