### ISSUE TITLE
Deal with package under review having no Rproj

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/pkgreviewr#9]
Sometimes the package under review will have the Rproj in the repo, sometimes not.

**Comment by katrinleinweber** [comment]
Hello :-) Is there a preference in the ROpenSci community whether to include the `.Rproj` or not?

**Comment by annakrystalli** [comment]
Het @katrinleinweber, I think it can vary for packages hosted on github. They're not included in the build but might exist in the source code. Anyroad, given the source code will always be a package, I've switch the function to get package metadata from `usethis:::project_data` to `usethis:::package_data` which I believe works off the `DESCRIPTION` file (5557d93bc31642b3132febd81d33c33fba60948a),

**Comment by katrinleinweber** [comment]
I was trying to lead up to the suggestion to prefer including it in the source code ;-)

Reason: a contributor's RStudio instance can pull out some useful style infos that harmonise collaboration. IMHO, `pkgreviewr` could spit out a warning if no `.Rproj` is present.

**Comment by annakrystalli** [comment]
Ah, I see. what sort of information were you thinking could be useful. In general the idea is that you use package reviewer to test the package under review locally in a separate project. So i don't think whether the package has an `.rproj` file or not matters too much atm?

**Comment by katrinleinweber** [comment]
Not for the review itself, but if `pkgreviewer` flagged a missing `.Rproj`, the reviewer and submitter could pre-emptively help future contributors. Doubling clicking the file opens the project's working directory in RStudio immediately (no `setwd()` necessary), and RStudio can immediately use the correct intendation for example. That's not super important, but worth a small flag / note.

**Comment by katrinleinweber** [comment]
PS: See also https://github.com/rstudio/rstudio/issues/1711. `.Rproj` is admittedly not the best file to ensure equal settings for contributors, because it mixes the rather personal `Workspace` & `History` settings in with `Space/Tab` settings etc. Once RStudio supports `.editorconfig`, this issue's topic would shift to that ;-)

**Comment by annakrystalli** [comment]
OK! I see what you are suggesting now! I guess it goes back to the original question about an rOpenSci review preference. Currently, as I understand it, it's not something that's checked at review. Maybe it should? Any thoughts @maelle ?
